version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-meubanco
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ifood-net

  app:
    build: .
    container_name: ifood-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meubanco
      SPRING_DATASOURCE_USERNAME: joao
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      CATALOG_SERVICE_URL: http://catalog-service:8082
    ports:
      - "8080:8080"
    networks:
      - ifood-net
  catalog-db:
    image: postgres:16
    container_name: catalog-postgres
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    ports:
      - "5434:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
      - ifood-net

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    depends_on:
      - catalog-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalog-db:5432/catalogdb
      SPRING_DATASOURCE_USERNAME: catalog
      SPRING_DATASOURCE_PASSWORD: catalog
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    networks:
      - ifood-net

volumes:
  postgres_data:
  catalog_data:

networks:
  ifood-net:
    driver: bridge
